// lib/daily-verses.ts

export const dailyVerses = {
  cs: [
    { text: "Hospodin je můj pastýř, nebudu mít nedostatek.", reference: "Žalm 23,1" },
    { text: "I když půjdu roklí šeré smrti, nebudu se bát ničeho zlého, vždyť se mnou jsi ty.", reference: "Žalm 23,4" },
    { text: "Miluj svého bližního jako sám sebe.", reference: "Leviticus 19,18" },
    { text: "Já jsem cesta, pravda i život. Nikdo nepřichází k Otci než skrze mne.", reference: "Jan 14,6" },
    { text: "Všechno mohu v Kristu, který mi dává sílu.", reference: "Filipským 4,13" },
    { text: "Neboť Bůh tak miloval svět, že dal svého jediného Syna.", reference: "Jan 3,16" },
    { text: "Hleďte, jak velikou lásku nám Otec daroval, že jsme nazváni dětmi Božími.", reference: "1 Jan 3,1" },
    { text: "V pokoji si lehnu a usnu, neboť ty sám, Hospodine, dáváš mi v bezpečí bydlet.", reference: "Žalm 4,9" },
    { text: "Hospodin ti požehná a ochrání tě, Hospodin ti ukáže svou tvář a smiluje se nad tebou.", reference: "Numeri 6,24-25" },
    { text: "Hle, já jsem s vámi po všecky dny až do skonání tohoto věku.", reference: "Matouš 28,20" },
    { text: "Všechno, co děláte, dělejte z lásky.", reference: "1 Korintským 16,14" },
    { text: "Hospodin je mé světlo a má spása, koho bych se bál?", reference: "Žalm 27,1" },
    { text: "A nyní zůstává víra, naděje, láska – ale největší z nich je láska.", reference: "1 Korintským 13,13" },
    { text: "Všechny své starosti vložte na něj, neboť mu na vás záleží.", reference: "1 Petr 5,7" },
    { text: "Hospodin je blízko všem, kdo ho vzývají.", reference: "Žalm 145,18" },
    { text: "Důvěřuj Hospodinu celým svým srdcem, na svoji rozumnost nespoléhej.", reference: "Přísloví 3,5" },
    { text: "Ať se děje cokoliv, děkujte, neboť to je Boží vůle.", reference: "1 Tesalonickým 5,18" },
    { text: "Pokoj vám zanechávám, svůj pokoj vám dávám.", reference: "Jan 14,27" },
    { text: "Vždyť my jsme jeho dílo, stvořeni v Kristu Ježíši k dobrým skutkům.", reference: "Efezským 2,10" },
    { text: "Radujte se v Pánu vždycky, znovu říkám, radujte se!", reference: "Filipským 4,4" },
    { text: "Přibližte se k Bohu a přiblíží se k vám.", reference: "Jakub 4,8" },
    { text: "Všechno má určenou chvíli a veškeré dění pod nebem svůj čas.", reference: "Kazatel 3,1" },
    { text: "Nedej se přemáhat zlem, ale přemáhej zlo dobrem.", reference: "Římanům 12,21" },
    { text: "Kdo je milosrdný k chudému, půjčuje Hospodinu.", reference: "Přísloví 19,17" },
    { text: "Hle, já jsem Hospodin, Bůh všeho tvorstva. Je mi něco nemožného?", reference: "Jeremjáš 32,27" },
    { text: "Každý ať dává podle toho, co se v srdci rozhodl, ne s nechutí ani z donucení; vždyť radostného dárce miluje Bůh.", reference: "2 Korintským 9,7" },
    { text: "Vy jste sůl země. Vy jste světlo světa.", reference: "Matouš 5,13-14" },
    { text: "Jděte do celého světa a kažte evangelium všemu stvoření.", reference: "Marek 16,15" },
    { text: "Proste, a bude vám dáno; hledejte, a naleznete; tlučte, a bude vám otevřeno.", reference: "Matouš 7,7" },
    { text: "Blaze těm, kdo pláčou, neboť oni budou potěšeni.", reference: "Matouš 5,4" },
    { text: "Blaze chudým v duchu, neboť jejich je království nebeské.", reference: "Matouš 5,3" },
    { text: "Blaze tichým, neboť oni dostanou zemi za dědictví.", reference: "Matouš 5,5" },
    { text: "Blaze těm, kdo hladovějí a žízní po spravedlnosti, neboť oni budou nasyceni.", reference: "Matouš 5,6" },
    { text: "Blaze milosrdným, neboť oni dojdou milosrdenství.", reference: "Matouš 5,7" },
    { text: "Blaze těm, kdo mají čisté srdce, neboť oni uzří Boha.", reference: "Matouš 5,8" },
    { text: "Blaze těm, kdo působí pokoj, neboť oni budou nazváni syny Božími.", reference: "Matouš 5,9" },
    { text: "Vy jste světlo světa. Nemůže zůstat skryto město ležící na hoře.", reference: "Matouš 5,14" },
    { text: "Ať tedy vaše světlo svítí před lidmi, aby viděli vaše dobré skutky a vzdali slávu vašemu Otci v nebesích.", reference: "Matouš 5,16" },
    { text: "Milujte své nepřátele a modlete se za ty, kdo vás pronásledují.", reference: "Matouš 5,44" },
    { text: "Buďte tedy dokonalí, jako je dokonalý váš nebeský Otec.", reference: "Matouš 5,48" },
    { text: "Váš nebeský Otec přece ví, co potřebujete, dřív než ho prosíte.", reference: "Matouš 6,8" },
    { text: "Odpusť nám naše viny, jako i my odpouštíme našim viníkům.", reference: "Matouš 6,12" },
    { text: "Nehromažďujte si poklady na zemi, kde je ničí mol a rez a kde zloději vykopávají a kradou.", reference: "Matouš 6,19" },
    { text: "Neboť kde je tvůj poklad, tam bude i tvé srdce.", reference: "Matouš 6,21" },
    { text: "Nemůžete sloužit Bohu i majetku.", reference: "Matouš 6,24" },
    { text: "Hledejte především jeho království a spravedlnost, a všechno ostatní vám bude přidáno.", reference: "Matouš 6,33" },
    { text: "Nesuďte, abyste nebyli souzeni.", reference: "Matouš 7,1" },
    { text: "Jak to, že vidíš třísku v oku svého bratra, ale trám ve vlastním oku nepozoruješ?", reference: "Matouš 7,3" },
    { text: "Každý, kdo prosí, dostává, a kdo hledá, nalézá, a kdo tluče, tomu bude otevřeno.", reference: "Matouš 7,8" },
    { text: "Jak byste chtěli, aby lidé jednali s vámi, tak vy jednejte s nimi.", reference: "Matouš 7,12" },
    { text: "Vejděte těsnou branou; neboť prostorná je brána a široká cesta, která vede do záhuby, a mnoho je těch, kdo tudy vcházejí.", reference: "Matouš 7,13" },
    { text: "Střežte se falešných proroků, kteří k vám přicházejí v ovčím rouchu, ale uvnitř jsou draví vlci.", reference: "Matouš 7,15" },
    { text: "Ne každý, kdo mi říká ‚Pane, Pane‘, vejde do království nebeského, ale ten, kdo činí vůli mého Otce v nebesích.", reference: "Matouš 7,21" },
    { text: "I kdybych procházel údolím smrti, nebudu se bát ničeho zlého, neboť ty se mnou jsi.", reference: "Žalm 23,4" },
    { text: "Hospodin je má síla a můj štít; mé srdce v něho doufá.", reference: "Žalm 28,7" },
    { text: "Hospodin je spravedlivý ve všech svých cestách a milostivý ve všech svých skutcích.", reference: "Žalm 145,17" },
    { text: "Chvalte Hospodina, neboť je dobrý, jeho milosrdenství je věčné.", reference: "Žalm 136,1" },
    { text: "Neboj se, neboť já jsem s tebou, nerozhlížej se úzkostlivě, já jsem tvůj Bůh.", reference: "Izajáš 41,10" },
    { text: "Povolal jsem tě tvým jménem, jsi můj.", reference: "Izajáš 43,1" },
    { text: "Hory mohou ustoupit a pahorky se otřásat, ale moje milosrdenství od tebe neodstoupí.", reference: "Izajáš 54,10" }
  ],
  en: [
    { text: "The Lord is my shepherd; I shall not want.", reference: "Psalm 23:1" },
    { text: "Even though I walk through the darkest valley, I will fear no evil, for you are with me.", reference: "Psalm 23:4" },
    { text: "Love your neighbor as yourself.", reference: "Leviticus 19:18" },
    { text: "I am the way and the truth and the life. No one comes to the Father except through me.", reference: "John 14:6" },
    { text: "I can do all this through him who gives me strength.", reference: "Philippians 4:13" },
    { text: "For God so loved the world that he gave his one and only Son.", reference: "John 3:16" },
    { text: "See what great love the Father has lavished on us, that we should be called children of God!", reference: "1 John 3:1" },
    { text: "In peace I will lie down and sleep, for you alone, Lord, make me dwell in safety.", reference: "Psalm 4:8" },
    { text: "The Lord bless you and keep you; the Lord make his face shine on you and be gracious to you.", reference: "Numbers 6:24-25" },
    { text: "And surely I am with you always, to the very end of the age.", reference: "Matthew 28:20" },
    { text: "Do everything in love.", reference: "1 Corinthians 16:14" },
    { text: "The Lord is my light and my salvation—whom shall I fear?", reference: "Psalm 27:1" },
    { text: "And now these three remain: faith, hope and love. But the greatest of these is love.", reference: "1 Corinthians 13:13" },
    { text: "Cast all your anxiety on him because he cares for you.", reference: "1 Peter 5:7" },
    { text: "The Lord is near to all who call on him.", reference: "Psalm 145:18" },
    { text: "Trust in the Lord with all your heart and lean not on your own understanding.", reference: "Proverbs 3:5" },
    { text: "Give thanks in all circumstances; for this is the will of God in Christ Jesus for you.", reference: "1 Thessalonians 5:18" },
    { text: "Peace I leave with you; my peace I give you.", reference: "John 14:27" },
    { text: "For we are God's handiwork, created in Christ Jesus to do good works.", reference: "Ephesians 2:10" },
    { text: "Rejoice in the Lord always. I will say it again: Rejoice!", reference: "Philippians 4:4" },
    { text: "Come near to God and he will come near to you.", reference: "James 4:8" },
    { text: "There is a time for everything, and a season for every activity under the heavens.", reference: "Ecclesiastes 3:1" },
    { text: "Do not be overcome by evil, but overcome evil with good.", reference: "Romans 12:21" },
    { text: "Whoever is kind to the poor lends to the Lord.", reference: "Proverbs 19:17" },
    { text: "I am the Lord, the God of all mankind. Is anything too hard for me?", reference: "Jeremiah 32:27" },
    { text: "Each of you should give what you have decided in your heart to give, not reluctantly or under compulsion, for God loves a cheerful giver.", reference: "2 Corinthians 9:7" },
    { text: "You are the salt of the earth. You are the light of the world.", reference: "Matthew 5:13-14" },
    { text: "Go into all the world and preach the gospel to all creation.", reference: "Mark 16:15" },
    { text: "Ask and it will be given to you; seek and you will find; knock and the door will be opened to you.", reference: "Matthew 7:7" },
    { text: "Blessed are those who mourn, for they will be comforted.", reference: "Matthew 5:4" },
    { text: "Blessed are the poor in spirit, for theirs is the kingdom of heaven.", reference: "Matthew 5:3" },
    { text: "Blessed are the meek, for they will inherit the earth.", reference: "Matthew 5:5" },
    { text: "Blessed are those who hunger and thirst for righteousness, for they will be filled.", reference: "Matthew 5:6" },
    { text: "Blessed are the merciful, for they will be shown mercy.", reference: "Matthew 5:7" },
    { text: "Blessed are the pure in heart, for they will see God.", reference: "Matthew 5:8" },
    { text: "Blessed are the peacemakers, for they will be called children of God.", reference: "Matthew 5:9" },
    { text: "You are the light of the world. A town built on a hill cannot be hidden.", reference: "Matthew 5:14" },
    { text: "Let your light shine before others, that they may see your good deeds and glorify your Father in heaven.", reference: "Matthew 5:16" },
    { text: "Love your enemies and pray for those who persecute you.", reference: "Matthew 5:44" },
    { text: "Be perfect, therefore, as your heavenly Father is perfect.", reference: "Matthew 5:48" },
    { text: "Your Father knows what you need before you ask him.", reference: "Matthew 6:8" },
    { text: "Forgive us our debts, as we also have forgiven our debtors.", reference: "Matthew 6:12" },
    { text: "Do not store up for yourselves treasures on earth, where moths and vermin destroy, and where thieves break in and steal.", reference: "Matthew 6:19" },
    { text: "For where your treasure is, there your heart will be also.", reference: "Matthew 6:21" },
    { text: "You cannot serve both God and money.", reference: "Matthew 6:24" },
    { text: "Seek first his kingdom and his righteousness, and all these things will be given to you as well.", reference: "Matthew 6:33" },
    { text: "Do not judge, or you too will be judged.", reference: "Matthew 7:1" },
    { text: "Why do you look at the speck of sawdust in your brother's eye and pay no attention to the plank in your own eye?", reference: "Matthew 7:3" },
    { text: "For everyone who asks receives; the one who seeks finds; and to the one who knocks, the door will be opened.", reference: "Matthew 7:8" },
    { text: "So in everything, do to others what you would have them do to you.", reference: "Matthew 7:12" },
    { text: "Enter through the narrow gate. For wide is the gate and broad is the road that leads to destruction, and many enter through it.", reference: "Matthew 7:13" },
    { text: "Watch out for false prophets. They come to you in sheep's clothing, but inwardly they are ferocious wolves.", reference: "Matthew 7:15" },
    { text: "Not everyone who says to me, 'Lord, Lord,' will enter the kingdom of heaven, but only the one who does the will of my Father who is in heaven.", reference: "Matthew 7:21" },
    { text: "Even though I walk through the darkest valley, I will fear no evil, for you are with me.", reference: "Psalm 23:4" },
    { text: "The Lord is my strength and my shield; my heart trusts in him.", reference: "Psalm 28:7" },
    { text: "The Lord is righteous in all his ways and faithful in all he does.", reference: "Psalm 145:17" },
    { text: "Give thanks to the Lord, for he is good; his love endures forever.", reference: "Psalm 136:1" },
    { text: "So do not fear, for I am with you; do not be dismayed, for I am your God.", reference: "Isaiah 41:10" },
    { text: "I have summoned you by name; you are mine.", reference: "Isaiah 43:1" },
    { text: "Though the mountains be shaken and the hills be removed, yet my unfailing love for you will not be shaken.", reference: "Isaiah 54:10" }
  ],
  ur: [
    { text: "خُداوند میرا چوپان ہے، مُجھے کسی چیز کی کمی نہ ہو گی۔", reference: "زبور ۲۳:۱" },
    { text: "اگرچہ مَیں موت کے سایہ کی وادی میں چلوں، توبھی کسی بَلا سے نہیں ڈروں گا کیونکہ تُو میرے ساتھ ہے۔", reference: "زبور ۲۳:۴" },
    { text: "اَپنے پڑوسی سے اَپنے برابر محبت رکھ۔", reference: "احبار ۱۹:۱۸" },
    { text: "مَیں راستہ، حق اَور زندگی ہُوں۔ کوئی میرے وسیلہ کے بغیر باپ کے پاس نہیں آتا۔", reference: "یوحنا ۱۴:۶" },
    { text: "مَیں وہ سب کچھ کر سکتا ہُوں جو مُجھے طاقت بخشتا ہے۔", reference: "فِلِپیّوں ۴:۱۳" },
    { text: "کیونکہ خُدا نے دُنیا سے اِتنی محبت رکھی کہ اُس نے اَپنا اِکلَوتا بیٹا بخش دیا۔", reference: "یوحنا ۳:۱۶" },
    { text: "دیکھو باپ نے ہم سے کیسی بڑی محبت کی ہے کہ ہم خُدا کے فرزند کہلائیں۔", reference: "۱ یوحنا ۳:۱" },
    { text: "مَیں سلامتی سے لیٹ جاؤں گا اور سو جاؤں گا کیونکہ اے خُداوند تُو ہی مُجھے اطمینان سے بسائے گا۔", reference: "زبور ۴:۸" },
    { text: "خُداوند تمہیں برکت دے اور تمہاری حفاظت کرے۔ خُداوند تم پر اپنا چہرہ روشن کرے اور تم پر مہربان ہو۔", reference: "گنتی ۶:۲۴-۲۵" },
    { text: "اَور دیکھو، مَیں دُنیا کے آخر تک ہمیشہ تمہارے ساتھ ہُوں۔", reference: "متی ۲۸:۲۰" },
    { text: "جو کچھ بھی کرو محبت سے کرو۔", reference: "۱ کرنتھیوں ۱۶:۱۴" },
    { text: "خُداوند میرا نور اَور نجات ہے، مَیں کس سے ڈروں؟", reference: "زبور ۲۷:۱" },
    { text: "اَور اَب یہ تین باقی ہیں: ایمان، اُمید اَور محبت۔ لیکن اِن میں سب سے بڑی محبت ہے۔", reference: "۱ کرنتھیوں ۱۳:۱۳" },
    { text: "اَپنی ساری فکریں اُس پر ڈال دو کیونکہ اُسے تمہاری پروا ہے۔", reference: "۱ پطرس ۵:۷" },
    { text: "خُداوند اُن سب کے نزدیک ہے جو اُسے پُکارتے ہیں۔", reference: "زبور ۱۴۵:۱۸" },
    { text: "اَپنے پورے دل سے خُداوند پر بھروسہ رکھ، اَور اَپنی عقل پر تکیہ نہ کر۔", reference: "امثال ۳:۵" },
    { text: "ہر حال میں شکر ادا کرو کیونکہ تُمہارے لیٔے خُدا کی مرضی یہی ہے۔", reference: "۱ تھسلنیکیوں ۵:۱۸" },
    { text: "مَیں تُمہیں اطمینان دے کر جاتا ہُوں، اَپنا اطمینان تُمہیں دیتا ہُوں۔", reference: "یوحنا ۱۴:۲۷" },
    { text: "کیونکہ ہم اُس کے بنائے ہویٔے ہیں، مسیح یسوع میں اچھے کاموں کے لیٔے پیدا کیے گیٔے۔", reference: "افسیوں ۲:۱۰" },
    { text: "خُداوند میں ہمیشہ خوش رہو، اَور مَیں پھر کہتا ہُوں، خوش رہو!", reference: "فِلِپیّوں ۴:۴" },
    { text: "خُدا کے نزدیک جاؤ تو وہ بھی تُمہارے نزدیک آئے گا۔", reference: "یعقوب ۴:۸" },
    { text: "ہر چیز کا ایک وقت ہے اَور آسمان کے نیچے ہر کام کا ایک موسم۔", reference: "واعظ ۳:۱" },
    { text: "برائی سے مغلوب نہ ہو، بَلکہ برائی کو نیکی سے مغلوب کر۔", reference: "رومیوں ۱۲:۲۱" },
    { text: "جو غریبوں پر ترس کھاتا ہے وہ خُداوند کو قرض دیتا ہے۔", reference: "امثال ۱۹:۱۷" },
    { text: "مَیں خُداوند ہُوں جو تمام بنی نوع آدم کا خُدا ہُوں۔ کیا میرے لیٔے کوئی کام مشکل ہے؟", reference: "یرمیاہ ۳۲:۲۷" },
    { text: "ہر کوئی جیسا اُس نے دل میں ٹھہرایا ہے ویسا ہی دے، نہ کہ دل گرفتگی سے اَور نہ مجبوراً، کیونکہ خُدا خوشی سے دینے والے سے محبت رکھتا ہے۔", reference: "۲ کرنتھیوں ۹:۷" },
    { text: "تُم زمین کے نمک ہو۔ تُم دُنیا کی روشنی ہو۔", reference: "متی ۵:۱۳-۱۴" },
    { text: "ساری دُنیا میں جا کر تمام مخلوقات کو خوشخبری سناؤ۔", reference: "مرقس ۱۶:۱۵" },
    { text: "مانگو تو تُمہیں دیا جائے گا، ڈھونڈو تو پاؤ گے، دروازہ کھٹکھٹاؤ تو تُمہارے لیٔے کھولا جائے گا۔", reference: "متی ۷:۷" },
    { text: "مُبارک ہیں وہ جو غمگین ہیں، کیونکہ وہ تسلّی پائیں گے۔", reference: "متی ۵:۴" },
    { text: "مُبارک ہیں وہ جو دل کے غریب ہیں، کیونکہ آسمان کی بادشاہی اُن ہی کی ہے۔", reference: "متی ۵:۳" },
    { text: "مُبارک ہیں وہ جو حلیم ہیں، کیونکہ وہ زمین کے وارث ہوں گے۔", reference: "متی ۵:۵" },
    { text: "مُبارک ہیں وہ جو راستبازی کے بھوکے اَور پیاسے ہیں، کیونکہ وہ آسُودہ ہوں گے۔", reference: "متی ۵:۶" },
    { text: "مُبارک ہیں وہ جو رحم کرنے والے ہیں، کیونکہ اُن پر رحم کیا جائے گا۔", reference: "متی ۵:۷" },
    { text: "مُبارک ہیں وہ جو پاک دل ہیں، کیونکہ وہ خُدا کو دیکھیں گے۔", reference: "متی ۵:۸" },
    { text: "مُبارک ہیں وہ جو صلح کراتے ہیں، کیونکہ وہ خُدا کے فرزند کہلائیں گے۔", reference: "متی ۵:۹" },
    { text: "تُم دُنیا کی روشنی ہو۔ جو شہر پہاڑ پر بسایا جائے وہ چھپ نہیں سکتا۔", reference: "متی ۵:۱۴" },
    { text: "تُمہاری روشنی اِس طرح لوگوں کے سامنے چمکے کہ وہ تُمہارے نیک کاموں کو دیکھ کر تُمہارے آسمانی باپ کی تمجید کریں۔", reference: "متی ۵:۱۶" },
    { text: "اَپنے دشمنوں سے محبت رکھو اَور اُن کے لیٔے دُعا کرو جو تُمہیں ستاتے ہیں۔", reference: "متی ۵:۴۴" },
    { text: "پس تُم کامل بنو جیسا تُمہارا آسمانی باپ کامل ہے۔", reference: "متی ۵:۴۸" },
    { text: "تُمہارا آسمانی باپ تُمہارے مانگنے سے پہلے ہی جانتا ہے کہ تُمہیں کیا ضرورت ہے۔", reference: "متی ۶:۸" },
    { text: "جس طرح ہم نے اَپنے قرض داروں کو معاف کیا ہے اُسی طرح تُو بھی ہمارے قرض معاف کر۔", reference: "متی ۶:۱۲" },
    { text: "اَپنے لیٔے زمین پر خزانے جمع نہ کرو جہاں کیڑا اَور زنگ خراب کرتے ہیں اَور جہاں چور نقب لگا کر چُراتے ہیں۔", reference: "متی ۶:۱۹" },
    { text: "کیونکہ جہاں تیرا خزانہ ہے وہیں تیرا دل بھی لگا رہے گا۔", reference: "متی ۶:۲۱" },
    { text: "تُم خُدا اَور دولت دونوں کی خدمت نہیں کر سکتے۔", reference: "متی ۶:۲۴" },
    { text: "پہلے اُس کی بادشاہی اَور راستبازی کی تلاش کرو تو یہ سب چیزیں بھی تُمہیں مل جائیں گی۔", reference: "متی ۶:۳۳" },
    { text: "عدالت مت کرو تاکہ تُم پر عدالت نہ کی جائے۔", reference: "متی ۷:۱" },
    { text: "تُو کیوں اَپنے بھایٔی کی آنکھ کا تنکا دیکھتا ہے مگر اَپنی آنکھ کا شہتیر نہیں دیکھتا؟", reference: "متی ۷:۳" },
    { text: "کیونکہ جو کوئی مانگتا ہے اُسے ملتا ہے اَور جو ڈھونڈتا ہے پاتا ہے اَور جو کھٹکھٹاتا ہے اُس کے لیٔے کھولا جاتا ہے۔", reference: "متی ۷:۸" },
    { text: "پس جو کچھ تُم چاہتے ہو کہ لوگ تُمہارے ساتھ کریں، تُم بھی اُن کے ساتھ ویسا ہی کرو۔", reference: "متی ۷:۱۲" },
    { text: "تنگ دروازے سے داخل ہو کیونکہ وہ دروازہ چوڑا اَور راستہ کشادہ ہے جو ہلاکت کو پہنچاتا ہے اَور بہت سے ہیں جو اُس سے داخل ہوتے ہیں۔", reference: "متی ۷:۱۳" },
    { text: "جھُوٹے نبیوں سے خبردار رہو جو بھیڑوں کے بھیس میں تُمہارے پاس آتے ہیں مگر باطن میں پھاڑنے والے بھیڑیے ہیں۔", reference: "متی ۷:۱۵" },
    { text: "ہر وہ شخص جو مُجھے 'خُداوند، خُداوند' کہتا ہے آسمان کی بادشاہی میں داخل نہیں ہو گا، صرف وہی جو میرے آسمانی باپ کی مرضی پر چلتا ہے۔", reference: "متی ۷:۲۱" },
    { text: "خُداوند میری چٹان، میرا قلعہ اَور میرا رہائی دہندہ ہے۔", reference: "زبور ۱۸:۲" },
    { text: "آسمان خُدا کے جلال کا بیان کر رہے ہیں اَور فضا اُس کی دستکاری کو ظاہر کر رہی ہے۔", reference: "زبور ۱۹:۱" },
    { text: "خُداوند میرا چرواہا ہے، مُجھے کسی چیز کی کمی نہ ہو گی۔", reference: "زبور ۲۳:۱" },
    { text: "زمین اَور اُس کی بھرپوری خُداوند کی ہے، دُنیا اَور اُس میں بسنے والے سب۔", reference: "زبور ۲۴:۱" },
    { text: "خُداوند میرے لیٔے نور اَور نجات ہے، مَیں کس سے ڈروں؟", reference: "زبور ۲۷:۱" },
    { text: "چکھو اَور دیکھو کہ خُداوند کیسا بھلا ہے! مُبارک ہے وہ شخص جو اُس میں پناہ لیتا ہے۔", reference: "زبور ۳۴:۸" },
    { text: "اَپنی راہ خُداوند کے سپرد کر، اُس پر بھروسہ رکھ، تو وہ اَپنا کام کرے گا۔", reference: "زبور ۳۷:۵" },
    { text: "خُداوند قریب ہے اُن سب کے جو اُسے پُکارتے ہیں، جو اُسے سچائی سے پُکارتے ہیں۔", reference: "زبور ۱۴۵:۱۸" },
    { text: "خداوند اپنے تمام کاموں میں راستباز ہے اَور اپنی تمام مخلوقات پر مہربان ہے۔", reference: "زبور ۱۴۵:۱۷" },
    { text: "خداوند کا شکر کرو کیونکہ وہ بھلا ہے، کیونکہ اُس کی شفقت ابدی ہے۔", reference: "زبور ۱۳۶:۱" }
  ]
};